spring:
  freemarker:
    check-template-location: false
  activiti:
    check-process-definitions: false
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
    open-in-view: true
    generate-ddl: true
  liquibase:
    enabled: true
    change-log: classpath:/META-INF/liquibase/activiti-app-db-changelog.xml
  aop:
    proxy-target-class: false
  datasource:
    url: jdbc:mysql://192.168.7.97:3306/activiti?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
  servlet:
    context-path: "/wf"
management:
  endpoints:
    web:
      exposure:
        include: "*"
